# -*- coding: utf-8 -*-
"""Movie_Recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTlrwIz8yJ01tDsgFNYXg25F8GXo2O-O
"""

!pip install pandas numpy scikit-learn nltk flask pyngrok requests

import pandas as pd
import numpy as np
import ast
import pickle
import requests

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from google.colab import files
uploaded = files.upload()

movies = pd.read_csv('/content/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/tmdb_5000_credits.csv')

movies.head()
credits.head()

movies = movies.merge(credits, on='title')
movies.shape

movies = movies[['movie_id','title','overview',
                 'genres','keywords','cast']]

"""# Data Cleaning"""

def convert(text):
    L=[]
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

movies['genres']=movies['genres'].apply(convert)
movies['keywords']=movies['keywords'].apply(convert)

"""Extraction of top 3 cast"""

def top_cast(text):
    L=[]
    counter=0

    for i in ast.literal_eval(text):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

movies['cast']=movies['cast'].apply(top_cast)

movies['overview']=movies['overview'].fillna('').apply(lambda x:x.split())

"""Removing spaces"""

for feature in ['genres','keywords','cast']:
    movies[feature]=movies[feature].apply(
        lambda x:[i.replace(" ","") for i in x]
    )

"""Creating tag columns"""

movies['tags']=movies['overview'] + \
               movies['genres'] + \
               movies['keywords'] + \
               movies['cast']

new_df = movies[['movie_id','title','tags']]

"""Convert list to string"""

new_df['tags']=new_df['tags'].apply(
    lambda x:" ".join(x)
)

new_df['tags']=new_df['tags'].apply(
    lambda x:x.lower()
)

"""# Vectorisation"""

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

vectors = tfidf.fit_transform(
    new_df['tags']
).toarray()

"""Cosine similarity"""

similarity = cosine_similarity(vectors)
similarity.shape

"""# Recommendation Function"""

def recommend(movie):
    movie = movie.lower()

    try:
        idx = new_df[
            new_df['title'].str.lower()==movie
        ].index[0]
    except:
        return "Movie not found"

    distances = similarity[idx]

    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x:x[1]
    )[1:6]

    result=[]

    for i in movie_list:
        result.append(
            new_df.iloc[i[0]].title
        )

    return result

recommend("Avatar")

"""Movie Poster Fetching"""

API_KEY = "0aa63bc8602d38e7673c4ab5ef41453c"

def fetch_poster(movie_id):
    url=f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={API_KEY}"
    data=requests.get(url).json()

    return "https://image.tmdb.org/t/p/w500/" + \
           data['poster_path']

def recommend_with_posters(movie):
    idx = new_df[
        new_df['title'].str.lower()==movie.lower()
    ].index[0]

    distances=similarity[idx]

    movie_list=sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x:x[1]
    )[1:6]

    names=[]
    posters=[]

    for i in movie_list:
        movie_id=new_df.iloc[i[0]].movie_id
        names.append(new_df.iloc[i[0]].title)
        posters.append(fetch_poster(movie_id))

    return names, posters

pickle.dump(new_df,
            open('movies.pkl','wb'))

pickle.dump(similarity,
            open('similarity.pkl','wb'))

pickle.dump(tfidf,
            open('vectorizer.pkl','wb'))

!pip install gradio

import gradio as gr

def movie_app(movie):
    return recommend(movie)

demo = gr.Interface(
    fn=movie_app,
    inputs=gr.Textbox(label="Enter movie"),
    outputs=gr.JSON(label="Recommendations"),
    title="Movie Recommendation System"
)

demo.launch(share=True)